#!/usr/bin/env python3
"""Generate questions.json from the official 2025 USCIS 128-question bank."""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from official_qa import parse_official

STARRED = {2, 7, 12, 20, 30, 36, 38, 39, 44, 52, 61, 66, 74, 78, 86, 94, 113, 115, 121, 126}
ALL_N = {10: 2, 48: 2, 65: 3, 67: 2, 69: 2, 81: 5, 126: 3}
STATE = {23: "senator", 29: "representative", 61: "governor", 62: "capital"}
OFFICIAL = {30: "speaker", 38: "president", 39: "vicePresident", 57: "chiefJustice"}


# Printed page numbers in One Nation, One People match PDF page numbers.
STUDY_RANGES = [
    (1, 15, 1, "The U.S. Constitution", 8),
    (16, 16, 2, "The Legislative Branch", 18),
    (17, 17, 3, "The Executive Branch", 24),
    (18, 35, 2, "The Legislative Branch", 18),
    (36, 49, 3, "The Executive Branch", 24),
    (50, 57, 4, "The Judicial Branch", 29),
    (58, 60, 5, "Rights and Responsibilities", 33),
    (61, 62, 6, "U.S. Geography", 38),
    (63, 72, 5, "Rights and Responsibilities", 33),
    (73, 75, 7, "Early American History", 43),
    (76, 80, 8, "The American Revolutionary War and the Declaration of Independence", 47),
    (81, 81, 6, "U.S. Geography", 38),
    (82, 91, 9, "A New Government and an Expanding Nation", 52),
    (92, 99, 10, "The Civil War", 58),
    (100, 116, 11, "American History: 1900 – 2001", 62),
    (117, 117, 7, "Early American History", 43),
    (118, 118, 11, "American History: 1900 – 2001", 62),
    (119, 128, 12, "American Symbols and Holidays", 69),
]


def study_guide(question_id: int) -> tuple[int, str, int]:
    for start, end, chapter, title, page in STUDY_RANGES:
        if start <= question_id <= end:
            return chapter, title, page
    return 1, "The U.S. Constitution", 8


def q(
    id_,
    section,
    topic,
    question,
    answers,
    extra,
):
    kind = "all_n" if id_ in ALL_N else "any_one"
    chapter, title, page = study_guide(id_)
    return {
        "id": id_,
        "section": section,
        "topic": topic,
        "question": question,
        "acceptedAnswers": answers,
        "extraInfo": extra,
        "starred6520": id_ in STARRED,
        "answerKind": kind,
        "minRequired": ALL_N.get(id_, 1),
        "currentOfficial": id_ in OFFICIAL,
        "stateSpecific": id_ in STATE,
        "stateField": STATE.get(id_) or OFFICIAL.get(id_),
        "studyGuideChapter": chapter,
        "studyGuideTitle": title,
        "studyGuidePage": page,
    }


AG = "AMERICAN GOVERNMENT"
AH = "AMERICAN HISTORY"
SH = "SYMBOLS AND HOLIDAYS"
P = "Principles of American Government"
S = "System of Government"
R = "Rights and Responsibilities"
C = "Colonial Period and Independence"
E = "1800s"
H = "Recent American History"
SY = "Symbols"
HO = "Holidays"

questions = [
    q(1, AG, P, "What is the form of government of the United States?",
      ["Republic", "Constitution-based federal republic", "Representative democracy",
       "Constitutional republic", "Federal republic"],
      "The United States is a constitution-based federal republic. The people elect representatives, and the Constitution limits government power."),
    q(2, AG, P, "What is the supreme law of the land?",
      ["The Constitution", "U.S. Constitution", "US Constitution", "United States Constitution", "Constitution"],
      "Article VI makes the Constitution the supreme law. Federal and state laws must follow it."),
    q(3, AG, P, "Name one thing the U.S. Constitution does.",
      ["Forms the government", "Defines powers of government", "Defines the parts of government",
       "Protects the rights of the people"],
      "The Constitution creates the federal government, divides its powers, and protects individual rights."),
    q(4, AG, P, "The U.S. Constitution starts with the words “We the People.” What does “We the People” mean?",
      ["Self-government", "Popular sovereignty", "Consent of the governed",
       "People should govern themselves", "Social contract", "Example of social contract"],
      "“We the People” means the government’s power comes from the people, not a king."),
    q(5, AG, P, "How are changes made to the U.S. Constitution?",
      ["Amendments", "The amendment process", "Amendment process"],
      "Article V lets Congress and the states amend the Constitution. There are 27 amendments."),
    q(6, AG, P, "What does the Bill of Rights protect?",
      ["The basic rights of Americans", "Basic rights of Americans",
       "The basic rights of people living in the United States",
       "Basic rights of people living in the United States", "Rights of Americans"],
      "The first ten amendments are the Bill of Rights. They protect freedoms such as speech, religion, and due process."),
    q(7, AG, P, "How many amendments does the U.S. Constitution have?",
      ["Twenty-seven", "27", "Twenty seven", "Twenty-seven (27)"],
      "There are 27 amendments. The first ten are the Bill of Rights (1791); the 27th was ratified in 1992."),
    q(8, AG, P, "Why is the Declaration of Independence important?",
      ["It says America is free from British control",
       "It says all people are created equal",
       "It identifies inherent rights",
       "It identifies individual freedoms"],
      "Adopted July 4, 1776, it announced independence and the idea that people have inherent rights."),
    q(9, AG, P, "What founding document said the American colonies were free from Britain?",
      ["Declaration of Independence", "The Declaration of Independence"],
      "The Declaration of Independence told the world the colonies were free from British rule."),
    q(10, AG, P, "Name two important ideas from the Declaration of Independence and the U.S. Constitution.",
      ["Equality", "Liberty", "Social contract", "Natural rights", "Limited government", "Self-government"],
      "Both documents rest on liberty, equality, natural rights, and government by consent."),
    q(11, AG, P, "The words “Life, Liberty, and the pursuit of Happiness” are in what founding document?",
      ["Declaration of Independence", "The Declaration of Independence"],
      "Jefferson wrote that people have unalienable rights, including life, liberty, and the pursuit of happiness."),
    q(12, AG, P, "What is the economic system of the United States?",
      ["Capitalism", "Free market economy", "Capitalist economy", "Market economy"],
      "The U.S. has a capitalist, free-market economy: private property, competition, and limited government control."),
    q(13, AG, P, "What is the rule of law?",
      ["Everyone must follow the law", "Leaders must obey the law",
       "Government must obey the law", "No one is above the law"],
      "Rule of law means the same laws apply to leaders and citizens. No one is above the law."),
    q(14, AG, P, "Many documents influenced the U.S. Constitution. Name one.",
      ["Declaration of Independence", "Articles of Confederation", "Federalist Papers",
       "Anti-Federalist Papers", "Virginia Declaration of Rights",
       "Fundamental Orders of Connecticut", "Mayflower Compact",
       "Iroquois Great Law of Peace"],
      "Earlier charters, the Articles of Confederation, and the Federalist Papers shaped the Constitution."),
    q(15, AG, P, "There are three branches of government. Why?",
      ["So one part does not become too powerful", "Checks and balances", "Separation of powers"],
      "Separation of powers and checks and balances keep any one branch from becoming too powerful."),
    q(16, AG, S, "Name the three branches of government.",
      ["Legislative, executive, and judicial", "Congress, president, and the courts",
       "Legislative executive judicial", "Congress president courts"],
      "Congress makes laws, the president enforces them, and the courts interpret them."),
    q(17, AG, S, "The President of the United States is in charge of which branch of government?",
      ["Executive branch", "The executive branch", "Executive"],
      "Article II gives the president the executive power to carry out federal laws."),
    q(18, AG, S, "What part of the federal government writes laws?",
      ["Congress", "U.S. Congress", "US Congress", "United States Congress",
       "Legislature", "National legislature", "Legislative branch"],
      "Only Congress—the Senate and House—can pass federal laws."),
    q(19, AG, S, "What are the two parts of the U.S. Congress?",
      ["Senate and House of Representatives", "Senate and House",
       "The Senate and the House", "House and Senate"],
      "Congress is bicameral: a 100-member Senate and a 435-member House."),
    q(20, AG, S, "Name one power of the U.S. Congress.",
      ["Writes laws", "Declares war", "Makes the federal budget",
       "Write laws", "Declare war", "Make the federal budget"],
      "Article I gives Congress power to legislate, tax, spend, and declare war."),
    q(21, AG, S, "How many U.S. senators are there?",
      ["One hundred", "100", "One hundred (100)", "Hundred"],
      "Each of the 50 states elects two senators, for 100 total."),
    q(22, AG, S, "How long is a term for a U.S. senator?",
      ["Six years", "6 years", "Six (6) years"],
      "Senators serve six-year terms. About one-third of the Senate is elected every two years."),
    q(23, AG, S, "Who is one of your state’s U.S. senators now?",
      ["Answers will vary", "No U.S. senators", "DC has no senators",
       "The territory has no senators"],
      "Each state has two senators. D.C. and territories have no U.S. senators. Add yours in Settings."),
    q(24, AG, S, "How many voting members are in the House of Representatives?",
      ["Four hundred thirty-five", "435", "Four hundred thirty five"],
      "There are 435 voting representatives, apportioned by state population after each census."),
    q(25, AG, S, "How long is a term for a member of the House of Representatives?",
      ["Two years", "2 years", "Two (2) years"],
      "Representatives serve two-year terms so they stay close to voters."),
    q(26, AG, S, "Why do U.S. representatives serve shorter terms than U.S. senators?",
      ["To more closely follow public opinion"],
      "Two-year House terms keep members accountable to current public opinion."),
    q(27, AG, S, "How many senators does each state have?",
      ["Two", "2", "Two (2)"],
      "The Constitution gives every state two senators, large or small."),
    q(28, AG, S, "Why does each state have two senators?",
      ["Equal representation", "Equal representation for small states",
       "The Great Compromise", "Connecticut Compromise", "Great Compromise"],
      "The Great Compromise gave states equal Senate votes and House seats by population."),
    q(29, AG, S, "Name your U.S. representative.",
      ["Answers will vary", "No voting representatives", "Delegate", "Resident Commissioner"],
      "You elect one representative for your congressional district. Add the name in Settings."),
    q(30, AG, S, "What is the name of the Speaker of the House of Representatives now?",
      ["Mike Johnson", "Johnson", "Speaker Johnson"],
      "The Speaker is elected by the House and is next in line after the vice president. Confirm at uscis.gov/citizenship/testupdates."),
    q(31, AG, S, "Who does a U.S. senator represent?",
      ["Citizens of their state", "People of their state", "Citizens of the state"],
      "Senators represent everyone in their state, not a single district."),
    q(32, AG, S, "Who elects U.S. senators?",
      ["Citizens from their state", "People of their state", "Voters in their state"],
      "The 17th Amendment lets the people of each state elect senators."),
    q(33, AG, S, "Who does a member of the House of Representatives represent?",
      ["Citizens in their congressional district", "Citizens in their district",
       "People from their congressional district", "People in their district"],
      "A representative speaks for the people of one congressional district."),
    q(34, AG, S, "Who elects members of the House of Representatives?",
      ["Citizens from their congressional district", "Citizens in their district",
       "Voters in their district"],
      "District voters elect their representative every two years."),
    q(35, AG, S, "Some states have more representatives than other states. Why?",
      ["Because of the state's population", "Because they have more people",
       "Because some states have more people", "State population", "They have more people"],
      "House seats are based on population. Larger states have more representatives."),
    q(36, AG, S, "The President of the United States is elected for how many years?",
      ["Four years", "4 years", "Four (4) years"],
      "Presidents serve four-year terms and may be elected to only two terms."),
    q(37, AG, S, "The President of the United States can serve only two terms. Why?",
      ["Because of the 22nd Amendment", "22nd Amendment",
       "To keep the president from becoming too powerful"],
      "The 22nd Amendment (1951) limits a president to two elected terms."),
    q(38, AG, S, "What is the name of the President of the United States now?",
      ["Donald J. Trump", "Donald Trump", "Trump", "Donald John Trump"],
      "The president is elected nationwide and leads the executive branch. Confirm the current name at uscis.gov/citizenship/testupdates."),
    q(39, AG, S, "What is the name of the Vice President of the United States now?",
      ["JD Vance", "J.D. Vance", "Vance", "James David Vance"],
      "The vice president is first in the line of succession and president of the Senate. Confirm at uscis.gov/citizenship/testupdates."),
    q(40, AG, S, "If the president can no longer serve, who becomes president?",
      ["The Vice President", "Vice President", "The Vice President of the United States"],
      "The 25th Amendment and Succession Act put the vice president first in line."),
    q(41, AG, S, "Name one power of the president.",
      ["Signs bills into law", "Vetoes bills", "Enforces laws",
       "Commander in Chief", "Commander in Chief of the military",
       "Chief diplomat", "Appoints federal judges"],
      "The president enforces laws, commands the military, and nominates federal judges."),
    q(42, AG, S, "Who is Commander in Chief of the U.S. military?",
      ["The President", "President", "The President of the United States"],
      "Article II makes the president Commander in Chief of the armed forces."),
    q(43, AG, S, "Who signs bills to become laws?",
      ["The President", "President", "The President of the United States"],
      "After both chambers pass a bill, the president may sign it into law or veto it."),
    q(44, AG, S, "Who vetoes bills?",
      ["The President", "President", "The President of the United States"],
      "A veto returns a bill to Congress. Congress can override with a two-thirds vote in each chamber."),
    q(45, AG, S, "Who appoints federal judges?",
      ["The President", "President", "The President of the United States"],
      "The president nominates federal judges; the Senate confirms them."),
    q(46, AG, S, "The executive branch has many parts. Name one.",
      ["President", "President of the United States", "Cabinet",
       "Federal departments and agencies", "Federal agencies"],
      "The executive branch includes the president, Cabinet, and federal agencies."),
    q(47, AG, S, "What does the President’s Cabinet do?",
      ["Advises the President", "Advises the President of the United States"],
      "Cabinet secretaries lead departments and advise the president."),
    q(48, AG, S, "What are two Cabinet-level positions?",
      ["Attorney General", "Secretary of Agriculture", "Secretary of Commerce",
       "Secretary of Education", "Secretary of Energy",
       "Secretary of Health and Human Services", "Secretary of Homeland Security",
       "Secretary of Housing and Urban Development", "Secretary of the Interior",
       "Secretary of Labor", "Secretary of State", "Secretary of Transportation",
       "Secretary of the Treasury", "Secretary of Veterans Affairs",
       "Secretary of War", "Secretary of Defense", "Vice President", "Vice-President",
       "Administrator of the Environmental Protection Agency",
       "Administrator of the Small Business Administration",
       "Director of the Central Intelligence Agency",
       "Director of the Office of Management and Budget",
       "Director of National Intelligence", "United States Trade Representative"],
      "Cabinet-level posts include the vice president and the heads of major departments and agencies."),
    q(49, AG, S, "Why is the Electoral College important?",
      ["It decides who is elected president",
       "It provides a compromise between the popular election of the president and congressional selection"],
      "States choose electors who formally elect the president. It balances popular and state-based selection."),
    q(50, AG, S, "What is one part of the judicial branch?",
      ["Supreme Court", "Federal Courts", "Federal court"],
      "The judicial branch is the Supreme Court and lower federal courts."),
    q(51, AG, S, "What does the judicial branch do?",
      ["Reviews laws", "Explains laws", "Resolves disputes about the law",
       "Resolves disagreements about the law",
       "Decides if a law goes against the Constitution",
       "Decides if a law goes against the U.S. Constitution"],
      "Courts interpret laws and can strike down laws that violate the Constitution (judicial review)."),
    q(52, AG, S, "What is the highest court in the United States?",
      ["Supreme Court", "The Supreme Court", "U.S. Supreme Court"],
      "The Supreme Court’s decisions are the last word on federal law and the Constitution."),
    q(53, AG, S, "How many seats are on the Supreme Court?",
      ["Nine", "9", "Nine (9)"],
      "Congress set the number at nine: one chief justice and eight associate justices."),
    q(54, AG, S, "How many Supreme Court justices are usually needed to decide a case?",
      ["Five", "5", "Five (5)"],
      "A majority of the justices who hear a case decides it—usually five of nine."),
    q(55, AG, S, "How long do Supreme Court justices serve?",
      ["For life", "Life", "Lifetime appointment", "Until retirement"],
      "Justices serve during “good Behaviour,” which in practice is a lifetime appointment."),
    q(56, AG, S, "Supreme Court justices serve for life. Why?",
      ["To be independent", "To be independent of politics",
       "To limit outside influence", "To limit outside political influence"],
      "Life tenure helps justices decide cases based on law, not elections."),
    q(57, AG, S, "Who is the Chief Justice of the United States now?",
      ["John Roberts", "John G. Roberts", "John G. Roberts, Jr.", "Roberts"],
      "The chief justice leads the Supreme Court and presides at presidential impeachment trials. Confirm at uscis.gov/citizenship/testupdates."),
    q(58, AG, S, "Name one power that is only for the federal government.",
      ["Print paper money", "Mint coins", "Declare war", "Create an army",
       "Make treaties", "Set foreign policy"],
      "The Constitution gives the national government exclusive powers such as coining money and declaring war."),
    q(59, AG, S, "Name one power that is only for the states.",
      ["Provide schooling and education", "Provide education", "Provide protection",
       "Provide police", "Provide safety", "Fire departments",
       "Give a driver's license", "Approve zoning and land use"],
      "The 10th Amendment reserves many powers to the states, including schools, police, and driver’s licenses."),
    q(60, AG, S, "What is the purpose of the 10th Amendment?",
      ["Powers not given to the federal government belong to the states or to the people",
       "It states that the powers not given to the federal government belong to the states or to the people"],
      "The 10th Amendment protects federalism: leftover powers stay with the states or the people."),
    q(61, AG, S, "Who is the governor of your state now?",
      ["Answers will vary", "DC does not have a governor"],
      "The governor is the state’s chief executive. D.C. does not have a governor. Add yours in Settings."),
    q(62, AG, S, "What is the capital of your state?",
      ["Answers will vary", "DC is not a state", "DC does not have a capital"],
      "Each state has a capital where the legislature meets. Add yours in Settings."),
    q(63, AG, R, "There are four amendments to the U.S. Constitution about who can vote. Describe one of them.",
      ["Citizens eighteen and older can vote", "Citizens 18 and older can vote",
       "You don't have to pay a poll tax to vote", "You don't have to pay to vote",
       "Any citizen can vote", "Women and men can vote",
       "A male citizen of any race can vote"],
      "The 15th, 19th, 24th, and 26th Amendments expanded voting rights and banned poll taxes."),
    q(64, AG, R, "Who can vote in federal elections, run for federal office, and serve on a jury in the United States?",
      ["Citizens", "Citizens of the United States", "U.S. citizens", "US citizens"],
      "These civic duties and rights belong to U.S. citizens."),
    q(65, AG, R, "What are three rights of everyone living in the United States?",
      ["Freedom of expression", "Freedom of speech", "Freedom of assembly",
       "Freedom to petition the government", "Freedom of religion", "The right to bear arms"],
      "Many Bill of Rights freedoms apply to everyone living in the United States, not only citizens."),
    q(66, AG, R, "What do we show loyalty to when we say the Pledge of Allegiance?",
      ["The United States", "The flag", "United States", "The US flag"],
      "The Pledge is a promise of loyalty to the United States and its flag."),
    q(67, AG, R, "Name two promises that new citizens make in the Oath of Allegiance.",
      ["Give up loyalty to other countries", "Defend the Constitution",
       "Defend the U.S. Constitution", "Obey the laws of the United States",
       "Serve in the military if needed", "Serve the nation if needed",
       "Be loyal to the United States"],
      "New citizens swear to support the Constitution, obey U.S. laws, and drop foreign allegiances."),
    q(68, AG, R, "How can people become United States citizens?",
      ["Be born in the United States", "Born in the United States",
       "Naturalize", "Naturalization", "Derive citizenship"],
      "Citizenship comes by birth under the 14th Amendment, naturalization, or derivation through parents."),
    q(69, AG, R, "What are two examples of civic participation in the United States?",
      ["Vote", "Run for office", "Join a political party", "Help with a campaign",
       "Join a civic group", "Join a community group",
       "Give an elected official your opinion", "Contact elected officials",
       "Support or oppose an issue or policy", "Write to a newspaper"],
      "Civic participation means taking part in public life—voting, campaigns, and speaking up."),
    q(70, AG, R, "What is one way Americans can serve their country?",
      ["Vote", "Pay taxes", "Obey the law", "Serve in the military",
       "Run for office", "Work for local, state, or federal government"],
      "Service includes voting, paying taxes, military service, and government work."),
    q(71, AG, R, "Why is it important to pay federal taxes?",
      ["Required by law", "All people pay to fund the federal government",
       "Required by the Constitution", "Required by the 16th Amendment", "Civic duty"],
      "The 16th Amendment allows a federal income tax, which funds national programs."),
    q(72, AG, R, "It is important for all men age 18 through 25 to register for the Selective Service. Name one reason why.",
      ["Required by law", "Civic duty", "Makes the draft fair if needed"],
      "Selective Service registration keeps a fair draft system ready if Congress ever authorizes one."),
    q(73, AH, C, "The colonists came to America for many reasons. Name one.",
      ["Freedom", "Political liberty", "Religious freedom", "Economic opportunity",
       "Escape persecution"],
      "Colonists sought religious freedom, political liberty, and economic opportunity."),
    q(74, AH, C, "Who lived in America before the Europeans arrived?",
      ["American Indians", "Native Americans", "Indigenous peoples"],
      "American Indian and Alaska Native nations lived here for thousands of years before Europeans."),
    q(75, AH, C, "What group of people was taken and sold as slaves?",
      ["Africans", "People from Africa"],
      "Millions of Africans were forced into slavery and brought to the Americas."),
    q(76, AH, C, "What war did the Americans fight to win independence from Britain?",
      ["American Revolution", "Revolutionary War", "American Revolutionary War",
       "War for American Independence", "War for Independence"],
      "The Revolutionary War (1775–1783) won independence from Britain."),
    q(77, AH, C, "Name one reason why the Americans declared independence from Britain.",
      ["High taxes", "Taxation without representation",
       "British soldiers stayed in Americans' houses", "Quartering", "Boarding",
       "They did not have self-government", "Boston Massacre",
       "Boston Tea Party", "Tea Act", "Stamp Act", "Sugar Act",
       "Townshend Acts", "Intolerable Acts", "Coercive Acts"],
      "Colonists protested taxes without representation, quartering, and limits on self-government."),
    q(78, AH, C, "Who wrote the Declaration of Independence?",
      ["Thomas Jefferson", "Jefferson"],
      "The Continental Congress asked Jefferson to draft the Declaration in 1776."),
    q(79, AH, C, "When was the Declaration of Independence adopted?",
      ["July 4, 1776", "July 4 1776", "4 July 1776", "July 4th 1776", "7/4/1776"],
      "Congress adopted the Declaration on July 4, 1776—now Independence Day."),
    q(80, AH, C, "The American Revolution had many important events. Name one.",
      ["Battle of Bunker Hill", "Bunker Hill", "Declaration of Independence",
       "Washington Crossing the Delaware", "Battle of Trenton",
       "Battle of Saratoga", "Saratoga", "Valley Forge",
       "Battle of Yorktown", "Yorktown", "British surrender at Yorktown"],
      "Key moments include Saratoga, Valley Forge, and the British surrender at Yorktown."),
    q(81, AH, C, "There were 13 original states. Name five.",
      ["New Hampshire", "Massachusetts", "Rhode Island", "Connecticut", "New York",
       "New Jersey", "Pennsylvania", "Delaware", "Maryland", "Virginia",
       "North Carolina", "South Carolina", "Georgia",
       "NH", "MA", "RI", "CT", "NY", "NJ", "PA", "DE", "MD", "VA", "NC", "SC", "GA"],
      "The thirteen colonies became the first states after independence."),
    q(82, AH, C, "What founding document was written in 1787?",
      ["The Constitution", "U.S. Constitution", "US Constitution", "Constitution"],
      "Delegates wrote the Constitution at the Philadelphia Convention in 1787."),
    q(83, AH, C, "The Federalist Papers supported the passage of the U.S. Constitution. Name one of the writers.",
      ["James Madison", "Madison", "Alexander Hamilton", "Hamilton",
       "John Jay", "Jay", "Publius"],
      "Hamilton, Madison, and Jay wrote the Federalist Papers under the name Publius."),
    q(84, AH, C, "Why were the Federalist Papers important?",
      ["They helped people understand the Constitution",
       "They helped people understand the U.S. Constitution",
       "They supported passing the Constitution",
       "They supported passing the U.S. Constitution"],
      "The essays explained the new Constitution and argued for ratification."),
    q(85, AH, C, "Benjamin Franklin is famous for many things. Name one.",
      ["Founded the first free public libraries", "First Postmaster General of the United States",
       "Helped write the Declaration of Independence", "Inventor", "U.S. diplomat",
       "US diplomat"],
      "Franklin was a printer, inventor, diplomat, and a framer of independence."),
    q(86, AH, C, "George Washington is famous for many things. Name one.",
      ["Father of Our Country", "First president of the United States",
       "General of the Continental Army", "President of the Constitutional Convention"],
      "Washington led the Continental Army, chaired the Convention, and became the first president."),
    q(87, AH, C, "Thomas Jefferson is famous for many things. Name one.",
      ["Writer of the Declaration of Independence", "Third president of the United States",
       "Doubled the size of the United States", "Louisiana Purchase",
       "First Secretary of State", "Founded the University of Virginia",
       "Writer of the Virginia Statute on Religious Freedom"],
      "Jefferson wrote the Declaration, bought Louisiana, and founded the University of Virginia."),
    q(88, AH, C, "James Madison is famous for many things. Name one.",
      ["Father of the Constitution", "Fourth president of the United States",
       "President during the War of 1812", "One of the writers of the Federalist Papers"],
      "Madison is called the Father of the Constitution and later served as the fourth president."),
    q(89, AH, C, "Alexander Hamilton is famous for many things. Name one.",
      ["First Secretary of the Treasury", "One of the writers of the Federalist Papers",
       "Helped establish the First Bank of the United States",
       "Aide to General George Washington", "Member of the Continental Congress"],
      "Hamilton built the early financial system and argued for the Constitution."),
    q(90, AH, E, "What territory did the United States buy from France in 1803?",
      ["Louisiana Territory", "Louisiana", "Louisiana Purchase"],
      "The Louisiana Purchase doubled U.S. land and opened the Mississippi River."),
    q(91, AH, E, "Name one war fought by the United States in the 1800s.",
      ["War of 1812", "Mexican-American War", "Civil War", "Spanish-American War"],
      "19th-century wars included 1812, the Mexican-American War, the Civil War, and 1898."),
    q(92, AH, E, "Name the U.S. war between the North and the South.",
      ["The Civil War", "Civil War"],
      "The Civil War (1861–1865) was fought over the Union, slavery, and secession."),
    q(93, AH, E, "The Civil War had many important events. Name one.",
      ["Battle of Fort Sumter", "Fort Sumter", "Emancipation Proclamation",
       "Battle of Vicksburg", "Vicksburg", "Battle of Gettysburg", "Gettysburg",
       "Sherman's March", "Surrender at Appomattox", "Appomattox",
       "Battle of Antietam", "Antietam", "Sharpsburg", "Lincoln was assassinated"],
      "Fort Sumter started the war; Gettysburg, Vicksburg, and Appomattox were turning points."),
    q(94, AH, E, "Abraham Lincoln is famous for many things. Name one.",
      ["Freed the slaves", "Emancipation Proclamation", "Saved the Union",
       "Preserved the Union", "Led the United States during the Civil War",
       "16th president of the United States", "Delivered the Gettysburg Address"],
      "Lincoln preserved the Union, issued the Emancipation Proclamation, and gave the Gettysburg Address."),
    q(95, AH, E, "What did the Emancipation Proclamation do?",
      ["Freed the slaves", "Freed slaves in the Confederacy",
       "Freed slaves in the Confederate states",
       "Freed slaves in most Southern states"],
      "In 1863 Lincoln declared freedom for enslaved people in Confederate-held territory."),
    q(96, AH, E, "What U.S. war ended slavery?",
      ["The Civil War", "Civil War"],
      "Union victory and the 13th Amendment ended legal slavery in the United States."),
    q(97, AH, E, "What amendment says all persons born or naturalized in the United States, and subject to the jurisdiction thereof, are U.S. citizens?",
      ["14th Amendment", "Fourteenth Amendment", "The 14th Amendment"],
      "The 14th Amendment (1868) defined birthright citizenship and equal protection."),
    q(98, AH, E, "When did all men get the right to vote?",
      ["After the Civil War", "During Reconstruction", "15th Amendment",
       "With the 15th Amendment", "1870"],
      "The 15th Amendment (1870) barred race-based denial of the vote for men."),
    q(99, AH, E, "Name one leader of the women’s rights movement in the 1800s.",
      ["Susan B. Anthony", "Anthony", "Elizabeth Cady Stanton", "Stanton",
       "Sojourner Truth", "Harriet Tubman", "Tubman", "Lucretia Mott", "Mott", "Lucy Stone"],
      "Leaders such as Stanton and Anthony organized for suffrage and equality."),
    q(100, AH, H, "Name one war fought by the United States in the 1900s.",
      ["World War I", "World War 1", "World War II", "World War 2",
       "Korean War", "Vietnam War", "Persian Gulf War", "Gulf War"],
      "The United States fought in both world wars, Korea, Vietnam, and the 1991 Gulf War."),
    q(101, AH, H, "Why did the United States enter World War I?",
      ["Because Germany attacked U.S. ships", "Because Germany attacked US civilian ships",
       "To support the Allied Powers", "To oppose the Central Powers"],
      "U-boat attacks on U.S. ships and support for the Allies led Congress to declare war in 1917."),
    q(102, AH, H, "When did all women get the right to vote?",
      ["1920", "After World War I", "19th Amendment", "With the 19th Amendment"],
      "The 19th Amendment (1920) guaranteed women the right to vote."),
    q(103, AH, H, "What was the Great Depression?",
      ["Longest economic recession in modern history",
       "The longest economic recession in modern history"],
      "The Great Depression was a severe, long economic collapse that began in 1929."),
    q(104, AH, H, "When did the Great Depression start?",
      ["The Great Crash", "The Great Crash 1929", "Stock market crash of 1929",
       "1929"],
      "It is marked by the 1929 stock market crash, also called the Great Crash."),
    q(105, AH, H, "Who was president during the Great Depression and World War II?",
      ["Franklin Roosevelt", "Franklin D. Roosevelt", "FDR", "Roosevelt"],
      "Franklin D. Roosevelt led the New Deal and wartime government from 1933 to 1945."),
    q(106, AH, H, "Why did the United States enter World War II?",
      ["Pearl Harbor", "Bombing of Pearl Harbor", "Japanese attacked Pearl Harbor",
       "To support the Allied Powers", "To oppose the Axis Powers"],
      "Japan’s attack on Pearl Harbor on December 7, 1941, brought the U.S. into the war."),
    q(107, AH, H, "Dwight Eisenhower is famous for many things. Name one.",
      ["General during World War II", "President at the end of the Korean War",
       "President during the Korean War", "34th president of the United States",
       "Signed the Federal-Aid Highway Act of 1956", "Created the Interstate System"],
      "Eisenhower commanded Allied forces in Europe and later created the Interstate Highway System."),
    q(108, AH, H, "Who was the United States’ main rival during the Cold War?",
      ["Soviet Union", "USSR", "Russia"],
      "After World War II the U.S. and the Soviet Union competed worldwide for decades."),
    q(109, AH, H, "During the Cold War, what was one main concern of the United States?",
      ["Communism", "Nuclear war"],
      "U.S. policy focused on containing communism and avoiding nuclear war."),
    q(110, AH, H, "Why did the United States enter the Korean War?",
      ["To stop the spread of communism"],
      "In 1950 the U.S. joined a U.N. effort to stop communist North Korea’s invasion of the South."),
    q(111, AH, H, "Why did the United States enter the Vietnam War?",
      ["To stop the spread of communism"],
      "U.S. leaders saw Vietnam as part of a wider effort to contain communism in Asia."),
    q(112, AH, H, "What did the civil rights movement do?",
      ["Fought to end racial discrimination"],
      "The movement used protests and the courts to challenge segregation and racial discrimination."),
    q(113, AH, H, "Martin Luther King, Jr. is famous for many things. Name one.",
      ["Fought for civil rights", "Worked for equality for all Americans",
       "Worked to ensure that people would not be judged by the color of their skin, but by the content of their character"],
      "King led nonviolent protests for civil rights and gave the “I Have a Dream” speech."),
    q(114, AH, H, "Why did the United States enter the Persian Gulf War?",
      ["To force the Iraqi military from Kuwait"],
      "In 1991 a U.S.-led coalition expelled Iraqi forces from Kuwait."),
    q(115, AH, H, "What major event happened on September 11, 2001 in the United States?",
      ["Terrorists attacked the United States",
       "Terrorists took over two planes and crashed them into the World Trade Center in New York City",
       "Terrorists took over a plane and crashed into the Pentagon in Arlington, Virginia",
       "Terrorists took over a plane originally aimed at Washington, D.C., and crashed in a field in Pennsylvania",
       "September 11", "9/11", "9-11", "Attack on the World Trade Center", "Pentagon attack"],
      "Al-Qaeda hijackers attacked the World Trade Center and the Pentagon; a fourth plane crashed in Pennsylvania."),
    q(116, AH, H, "Name one U.S. military conflict after the September 11, 2001 attacks.",
      ["Global War on Terror", "War on Terror", "War in Afghanistan", "War in Iraq"],
      "The U.S. fought in Afghanistan and Iraq as part of the post-9/11 War on Terror."),
    q(117, AH, H, "Name one American Indian tribe in the United States.",
      ["Apache", "Blackfeet", "Cayuga", "Cherokee", "Cheyenne", "Chippewa",
       "Choctaw", "Creek", "Crow", "Hopi", "Huron", "Inupiat", "Lakota",
       "Mohawk", "Mohegan", "Navajo", "Oneida", "Onondaga", "Pueblo",
       "Seminole", "Seneca", "Shawnee", "Sioux", "Teton", "Tuscarora"],
      "Hundreds of tribal nations are in the United States today. USCIS lists many acceptable names."),
    q(118, AH, H, "Name one example of an American innovation.",
      ["Light bulb", "Automobile", "Cars", "Internal combustion engine",
       "Skyscrapers", "Airplane", "Assembly line", "Landing on the moon",
       "Integrated circuit", "IC"],
      "U.S. innovations include the light bulb, assembly line, airplane, and the moon landing."),
    q(119, SH, SY, "What is the capital of the United States?",
      ["Washington, D.C.", "Washington DC", "Washington D.C.", "Washington"],
      "The federal capital has been Washington, D.C., since 1800."),
    q(120, SH, SY, "Where is the Statue of Liberty?",
      ["New York", "New York Harbor", "Liberty Island", "New Jersey",
       "Near New York City", "Hudson River", "On the Hudson"],
      "The statue stands on Liberty Island in New York Harbor, a gift from France in 1886."),
    q(121, SH, SY, "Why does the flag have 13 stripes?",
      ["Because there were 13 original colonies",
       "Because the stripes represent the original colonies",
       "13 original colonies", "Original colonies"],
      "The 13 stripes honor the original colonies that became the first states."),
    q(122, SH, SY, "Why does the flag have 50 stars?",
      ["Because there is one star for each state",
       "Because each star represents a state",
       "Because there are 50 states", "One star for each state", "50 states"],
      "Each star stands for one of the 50 states."),
    q(123, SH, SY, "What is the name of the national anthem?",
      ["The Star-Spangled Banner", "Star-Spangled Banner", "Star Spangled Banner"],
      "Francis Scott Key wrote the poem after the 1814 bombardment of Fort McHenry."),
    q(124, SH, SY, "The Nation’s first motto was “E Pluribus Unum.” What does that mean?",
      ["Out of many, one", "We all become one"],
      "The Latin motto means many people and states form one nation."),
    q(125, SH, HO, "What is Independence Day?",
      ["A holiday to celebrate U.S. independence from Britain",
       "A holiday to celebrate US independence",
       "The country's birthday", "Independence Day", "July 4", "The Fourth of July"],
      "July 4 celebrates the 1776 Declaration of Independence."),
    q(126, SH, HO, "Name three national U.S. holidays.",
      ["New Year's Day", "Martin Luther King, Jr. Day", "Martin Luther King Jr Day",
       "Presidents Day", "Washington's Birthday", "Memorial Day", "Juneteenth",
       "Independence Day", "Labor Day", "Columbus Day", "Veterans Day",
       "Thanksgiving Day", "Thanksgiving", "Christmas Day", "Christmas"],
      "Federal holidays honor historic events and people, from New Year’s Day to Christmas."),
    q(127, SH, HO, "What is Memorial Day?",
      ["A holiday to honor soldiers who died in military service",
       "Honors soldiers who died", "Honors the war dead"],
      "Memorial Day (the last Monday in May) honors those who died in U.S. military service."),
    q(128, SH, HO, "What is Veterans Day?",
      ["A holiday to honor people in the U.S. military",
       "A holiday to honor people in the military",
       "A holiday to honor people who have served in the U.S. military",
       "A holiday to honor people who have served in the military",
       "Honors veterans", "Honors people who served in the military"],
      "Veterans Day (November 11) honors all who have served in the U.S. armed forces."),
]

assert [x["id"] for x in questions] == list(range(1, 129)), "Need questions 1-128"
assert sum(1 for x in questions if x["starred6520"]) == 20

root = Path(__file__).resolve().parents[1]
official = parse_official(root / "core/src/test/resources/official-128.txt")
assert set(official) == set(range(1, 129)), f"Official parse missed {set(range(1, 129)) - set(official)}"
for item in questions:
    item["officialAnswers"] = official[item["id"]]

payload = json.dumps(questions, indent=2, ensure_ascii=False) + "\n"
for dest in (
    root / "core/src/main/resources/questions.json",
    root / "app/src/main/assets/questions.json",
):
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(payload, encoding="utf-8")
    print(f"Wrote {len(questions)} questions to {dest}")
